### PR TITLE
Port to pion/webrtc@v2.0.0

### PR DESCRIPTION
**Pull request by Sean-Der**
Hey @maxmcd 
We just released v2.0.0 and I am taking a shot at porting projects to make sure we didn't miss anything :)

### CODE REVIEW

**Comment by maxmcd** [comment]
@Sean-Der thanks so much!

Will confirm functionality and push this as a new release.

**Comment by Sean-Der** [comment]
Nice! I used it and worked for me `CLI <-> CLI` and `CLI <-> Browser (Chromium)`

Thanks again for building this, it brought a lot of positive attention our way :)

**Comment by Sean-Der** [comment]
Hey @maxmcd 
Updated to a new dot release.

`v2` has pretty substantial ICE and SCTP improvements. I think a few of the issues filed might be resolved just by taking the update.

thanks!

**Comment by Sean-Der** [comment]
Hey!

I am going to be talking about WebTTY at https://allthingsrtc.org/ (good example of what interesting things you can build with WebRTC)

Anything I can do to get this merged before then? I just want people using the `v2` API before then.

**Comment by maxmcd** [comment]
agh, sorry, just missed it

merged, sending out a new release now

**Pull request merged**
